# Generated by Django 4.2.1 on 2023-05-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInstance',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('booked_at_time', models.DateTimeField(auto_now_add=True)),
                ('lead_passenger_contact_email', models.CharField(max_length=100)),
                ('lead_passenger_contact_number', models.CharField(max_length=15)),
                ('total_booking_cost', models.FloatField()),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('transaction_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=255)),
                ('longitude', models.FloatField(max_length=50)),
                ('latitude', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('flight_ticket_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('num_available_seats', models.IntegerField()),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_location', to='mainapp.country')),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_location', to='mainapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('max_capacity', models.IntegerField()),
                ('max_flight_distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatInstance',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('seat_name', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flightinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('passport_num', models.CharField(max_length=25)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bookinginstance')),
                ('nationality_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seatinstance')),
            ],
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plane'),
        ),
    ]
